vim.api.nvim_command('let g:solarized_termcolors=256')
vim.api.nvim_command('set background=dark')
vim.api.nvim_command('colorscheme github_*')

vim.api.nvim_command('highlight Normal guibg=none')
vim.api.nvim_command('highlight NonText guibg=none')
vim.api.nvim_command('highlight TabLine guibg=none')
vim.api.nvim_command('highlight TabLineFill guibg=none')
vim.api.nvim_command('highlight StatusLine guibg=none')
vim.api.nvim_command('highlight StatusLineNC guibg=none')
vim.api.nvim_command('highlight CursorColumn guibg=none')
vim.api.nvim_command('highlight CursorLine guibg=none')
vim.api.nvim_command('highlight NormalNC guibg=none')
vim.api.nvim_command('highlight VertSplit guibg=none')
vim.api.nvim_command('highlight TelescopeNormal guibg=none')
vim.api.nvim_command('highlight TelescopePromptNormal guibg=none')
vim.api.nvim_command('highlight TelescopePreviewNormal guibg=none')

vim.api.nvim_command('highlight clear LineNr')
vim.api.nvim_command('highlight clear SignColumn')
